-- Migration simplifiée pour la gestion locative

-- 1. COLONNES DE BRANDING SUR PROFILES
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS logo_url TEXT,
ADD COLUMN IF NOT EXISTS signature_url TEXT,
ADD COLUMN IF NOT EXISTS company_name TEXT,
ADD COLUMN IF NOT EXISTS company_address TEXT,
ADD COLUMN IF NOT EXISTS company_phone TEXT,
ADD COLUMN IF NOT EXISTS company_email TEXT,
ADD COLUMN IF NOT EXISTS company_ninea TEXT;

-- 2. COLONNES MANQUANTES SUR LEASES
ALTER TABLE leases 
ADD COLUMN IF NOT EXISTS property_address TEXT,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- 3. COLONNE CATEGORY SUR MAINTENANCE_REQUESTS
ALTER TABLE maintenance_requests
ADD COLUMN IF NOT EXISTS category TEXT;
